[package]
name = "eq_sat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.9.3"

[[bin]]
name = "test"
test = false

[lib]
name = "lang"
path = "src/lib/mod.rs"
